# Generated by Django 4.0.5 on 2023-11-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id_emprendimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_emprendimiento', models.CharField(max_length=128)),
                ('email_emprendimiento', models.EmailField(max_length=254)),
                ('telefono_emprendimiento', models.CharField(max_length=15)),
                ('descripcion_emprendimiento', models.TextField()),
                ('ubicacion_emprendimiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_servicio', models.CharField(max_length=20)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion_servicio', models.TextField()),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disponibilidad_servicio', models.BooleanField()),
                ('id_emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emprendimiento.emprendimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_producto', models.CharField(max_length=20)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.TextField()),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_producto', models.PositiveIntegerField()),
                ('id_emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emprendimiento.emprendimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id_emprendedor', models.AutoField(primary_key=True, serialize=False)),
                ('nro_identificacion_emprendedor', models.CharField(max_length=20)),
                ('nombre_emprendedor', models.CharField(max_length=128)),
                ('apellido_emprendedor', models.CharField(max_length=100)),
                ('email_emprendedor', models.EmailField(max_length=254)),
                ('telefono_emprendedor', models.CharField(max_length=15)),
                ('id_emprendimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='emprendimiento.emprendimiento')),
            ],
        ),
    ]
