# Generated by Django 4.0.5 on 2023-11-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(blank=True, null=True, upload_to='up_images/'),
        ),
    ]
