# Generated by Django 4.0.5 on 2023-11-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='img_emprendimiento',
            field=models.ImageField(blank=True, null=True, upload_to='ent_logo_images/'),
        ),
    ]
