# Generated by Django 4.0.5 on 2023-11-18 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0004_emprendimiento_img_emprendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='img_emprendimiento',
            field=models.ImageField(blank=True, null=True, upload_to='ent_logo_images'),
        ),
    ]
