# Generated by Django 4.0.5 on 2023-11-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0006_emprendimiento_usuario_emprendedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprendedor',
        ),
    ]
